# Generated by Django 5.1.3 on 2024-11-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_name_medicine_model_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine_model',
            name='Quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
